package com.remotemonitor.watch.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import com.remotemonitor.watch.api.Iso8601Timestamp
import com.squareup.moshi.Json

/**
 * Local measurement record (REQ-WATCH-06).
 *
 * Primary key is `localId` (UUID v4, client-generated per D5 in obs #249),
 * which is the idempotency key for the backend.
 *
 * **No sync-state column** (per design D3): presence-in-table = pending upload.
 * After a 2xx response that echoes the `localId` in `accepted_ids`, the row
 * is deleted.
 *
 * The Room schema is exported to `app/schemas/` via the `room.schemaLocation`
 * KSP argument configured in `app/build.gradle.kts` (T-WATCH-18). The
 * schema JSON is generated by the Room compiler and never hand-written.
 *
 * **Wire shape (T-FIX-04, REQ-WATCH-52)**: the @Json(name=...) annotations
 * align the Moshi wire keys with the OpenAPI `MeasurementBatch` schema
 * (snake_case). The `timestamp` field carries @Iso8601Timestamp so the
 * `Long` epoch ms at rest is serialized as an ISO 8601 `datetime` string
 * with a `Z` suffix on the wire — that is what Pydantic's
 * `extra="forbid"` validation expects. Room ignores `@Json` (and any
 * other non-`@ColumnInfo` annotation) — the same precedent as
 * `BatchResponse` carrying `@Json` while sitting next to Room entities.
 *
 * **`ibis_ms` (REQ-WATCH-HR-IBI-10)**: the new `ibisMs: List<Long>?`
 * column is persisted via [IbiListConverter], registered as a
 * per-entity `@TypeConverters`. The converter stores the list as a
 * JSON string (text affinity column) so the on-disk shape matches
 * the wire shape (Moshi's default `List<Long>` -> JSON array of
 * integers). End-to-end: a row with `ibisMs = [800L, 820L]` writes
 * the column `"[800,820]"` and reads it back to the same list. The
 * field is appended at the END of the parameter list with a default
 * of `null` so existing call sites compile unchanged.
 */
@Entity(
    tableName = "measurements",
    indices = [Index(value = ["timestamp"])],
)
@TypeConverters(IbiListConverter::class)
data class MeasurementEntity(
    @PrimaryKey
    @ColumnInfo(name = "local_id")
    @Json(name = "local_id")
    val localId: String,
    @ColumnInfo(name = "timestamp")
    @Json(name = "timestamp")
    @Iso8601Timestamp
    val timestamp: Long,
    @ColumnInfo(name = "heart_rate_bpm")
    @Json(name = "heart_rate_bpm")
    val heartRateBpm: Int?,
    @ColumnInfo(name = "spo2_percent")
    @Json(name = "spo2_percent")
    val spo2Percent: Double?,
    @ColumnInfo(name = "ibis_ms")
    @Json(name = "ibis_ms")
    val ibisMs: List<Long>? = null,
)
