package com.remotemonitor.watch.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Local measurement record (REQ-WATCH-06).
 *
 * Primary key is `localId` (UUID v4, client-generated per D5 in obs #249),
 * which is the idempotency key for the backend.
 *
 * **No sync-state column** (per design D3): presence-in-table = pending upload.
 * After a 2xx response that echoes the `localId` in `accepted_ids`, the row
 * is deleted.
 *
 * The Room schema is exported to `app/schemas/` via the `room.schemaLocation`
 * KSP argument configured in `app/build.gradle.kts` (T-WATCH-18). The
 * schema JSON is generated by the Room compiler and never hand-written.
 */
@Entity(
    tableName = "measurements",
    indices = [Index(value = ["timestamp"])],
)
data class MeasurementEntity(
    @PrimaryKey
    @ColumnInfo(name = "local_id")
    val localId: String,
    @ColumnInfo(name = "timestamp")
    val timestamp: Long,
    @ColumnInfo(name = "heart_rate_bpm")
    val heartRateBpm: Int?,
    @ColumnInfo(name = "spo2_percent")
    val spo2Percent: Double?,
)
