"""Alembic environment.

Wired to read the async database URL from `app.config.settings`. Sets
up `pgcrypto` and the three project schemas (`pii`, `clinical`,
`audit`) before any migration runs so that autogenerated CREATE TABLE
statements can land in the right schemas without each migration having
to manage the setup itself.

The schema objects are NOT placed in the migration files. Per project
convention, migrations are CLI-generated (`alembic revision
--autogenerate`) and never hand-edited — the alembic env is the only
place that owns non-table setup.
"""
from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool, text
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

# Imported here so a missing APP_* env file fails loudly at migration time
# rather than silently at table-create time.
from app.config import settings

config = context.config

# Override the (empty) sqlalchemy.url from alembic.ini with the value
# managed by pydantic-settings.
config.set_main_option("sqlalchemy.url", settings.database_url)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

from app.models import Base

target_metadata = Base.metadata  # 4 tables across pii / clinical / audit.

# Pre-migration setup that must exist before any table can be created in
# the right schema. Idempotent — runs inside the migration transaction so
# the setup rolls back together with the migration body. Emitted in
# offline mode too so a generated SQL script bootstraps a fresh database.
_PRE_MIGRATION_SETUP = (
    "CREATE EXTENSION IF NOT EXISTS pgcrypto",
    "CREATE SCHEMA IF NOT EXISTS pii",
    "CREATE SCHEMA IF NOT EXISTS clinical",
    "CREATE SCHEMA IF NOT EXISTS audit",
)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (emit SQL without a live DB)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        for stmt in _PRE_MIGRATION_SETUP:
            context.execute(stmt)
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        for stmt in _PRE_MIGRATION_SETUP:
            connection.execute(text(stmt))
        context.run_migrations()


async def run_migrations_online() -> None:
    """Run migrations in 'online' mode using an async engine."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
