/**
 * Theme color constants for Recharts and other libraries that need
 * literal color strings (Recharts `stroke` / `fill` props, SVG attributes,
 * canvas, etc.).
 *
 * Mirrors the design tokens defined in `app/styles.css` under the
 * `@theme` block. CSS variables generated by Tailwind v4 are not directly
 * accessible from JS at module-evaluation time, so we duplicate the values
 * here and treat this file as the **single source of truth** for any
 * non-CSS color usage.
 *
 * Source: remote-monitor design system "Iris Void" — adapted from Dala.
 *   See `/design/DESIGN.md` for the full reference lock and token roles.
 *
 * TOKEN ROLE LOCK (must be preserved):
 *   - electric-iris (#8052FF): CTA filled buttons ONLY — never backgrounds, borders, or surfaces
 *   - saffron-spark (#FFB829): emphasis text + warn state
 *   - mint-vital (#00FFAA): ok/live state ONLY
 *   - bone-white (#FFFFFF): typography ONLY
 *   - ash-gray / silver-mist: typography hierarchy ONLY
 *
 * If a value changes in `styles.css`, update this file too.
 */

/* ─── Surfaces (Dala flat hierarchy) ─────────────────────────────── */

/** Page canvas — the void. */
export const surface = '#000000'

/** Card background — same as canvas in Dala, separated only by border. */
export const panel = '#000000'

/** Hover / disabled fill (slightly lifted from void). */
export const surfaceSubtle = '#0A0A0A'

/* ─── Foreground ink ──────────────────────────────────────────────── */

/** Primary text — bone-white. */
export const inkPrimary = '#FFFFFF'

/** Helper text — silver-mist. */
export const inkMuted = '#BDBDBD'

/** Secondary text, labels — ash-gray. */
export const inkFaint = '#9A9A9A'

/* ─── Borders ────────────────────────────────────────────────────── */

/** Subtle card border — deep-verdant (the only chrome with chroma). */
export const border = '#15846E'

/** Stronger separation — used on hover / focus. */
export const borderStrong = '#1F5A4A'

/** Lifted grid lines for charts. */
export const gridLight = '#1A1A1A'

/* ─── Accent (electric iris — CTA only) ───────────────────────────── */

/** CTA / link / active state. NEVER as a surface. */
export const accent = '#8052FF'

/** Hover state — darker iris. */
export const accentStrong = '#5E3FCC'

/** Selected background — iris wash on black. */
export const accentSoft = '#1F1545'

/* ─── Emphasis (saffron spark) ───────────────────────────────────── */

/** Highlight text + warn state. */
export const emphasis = '#FFB829'

/* ─── Status colors (clinical domain) ────────────────────────────── */

/** Ok / healthy range / connected. */
export const statusOk = '#00FFAA'

/** Warn — pending, caution. */
export const statusWarn = '#FFB829'

/** Danger — critical. Kept standard red for clarity. */
export const statusDanger = '#EF4444'

/** Info — informational. */
export const statusInfo = '#8052FF'

/* ─── Chart palette (HRV bands + line series) ─────────────────────── */

/** Primary data series — electric iris. */
export const chartLine = '#8052FF'

/** Latest / most recent point — saffron spark (amber pulse). */
export const chartLineLatest = '#FFB829'

/** Axis labels — ash-gray. */
export const chartAxis = '#9A9A9A'

/** Grid lines — barely visible lift off the void. */
export const chartGrid = '#1A1A1A'

/** Reference / identity lines — silver-mist. */
export const chartIdentity = '#BDBDBD'

/** VLF frequency band — electric iris. */
export const chartVlf = '#8052FF'

/** LF frequency band — saffron spark. */
export const chartLf = '#FFB829'

/** HF frequency band — mint vital. */
export const chartHf = '#00FFAA'

/** Mark a single most-recent beat (Poincaré plot). */
export const chartBeatNewest = '#BDBDBD'

/* ─── Recharts tooltip (max 2 colors per component) ──────────────── */

/**
 * Shared `contentStyle` object for Recharts `<Tooltip />` across the
 * three clinical charts (tachogram, frequency, Poincaré). Strict
 * restraint: background + border + text only — no gradient, no shadow.
 */
export const TOOLTIP_STYLE = {
  backgroundColor: panel,
  border: `1px solid ${border}`,
  borderRadius: 24,
  boxShadow: 'none',
  fontSize: 12,
  color: inkPrimary,
} as const